spring:
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/be6_3runner_dev
    username: be6_3runner
    password: tHos2g5st4@XH7mT
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: 3runner-batch
  profiles:
    active: dev
  rabbitmq:
    host: 133.186.241.167
    port: 5672
    username: admin
    password: nhnacademy123!

# Log Level 설정
logging:
  level:
    root: info
