spring:
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/be6_3runner_dev
    username: be6_3runner
    password: tHos2g5st4@XH7mT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      max-total: 20
      max-idle: 20
      min-idle: 5
      test-on-borrow: true
      validation-query: SELECT 1

  application:
    name: 3runner-batch
  profiles:
    active: prod
  rabbitmq:
    host: 133.186.241.167
    port: 6379
    username: admin
    password: nhnacademy123!

# Log Level 설정
logging:
  level:
    root: info
